# Generated by Django 3.1.2 on 2020-12-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201113_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('coursename', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('minq', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
