# Generated by Django 3.1.2 on 2020-12-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('coursename', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
