# Generated by Django 3.1.2 on 2020-12-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coursecode',
        ),
        migrations.RemoveField(
            model_name='course',
            name='email',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
    ]
