# Generated by Django 3.1.2 on 2020-12-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20201218_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='caption',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
