# Generated by Django 3.1.2 on 2020-12-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_course_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursename',
            new_name='coursecode',
        ),
    ]
