# Generated by Django 3.1.2 on 2020-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20201218_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='caption',
        ),
        migrations.AddField(
            model_name='course',
            name='captio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
