# Generated by Django 3.1.2 on 2020-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20201218_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('coursecode', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=50, null=True)),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
            options={
                'db_table': 'videoentry',
            },
        ),
    ]
