# Generated by Django 3.1.2 on 2020-12-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_videoentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
