# Generated by Django 3.1.2 on 2020-12-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='doubt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('su_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'doubt',
            },
        ),
    ]
