# Generated by Django 3.1.2 on 2020-12-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_doubt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubt',
            name='name',
        ),
        migrations.AddField(
            model_name='doubt',
            name='coursecode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
