# Generated by Django 3.1.2 on 2020-12-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20201221_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='post',
            field=models.CharField(max_length=50),
        ),
    ]
